Cleanup in run scripts
Signed-off-by: Evgeniy Didin <Evgeniy.Didin@synopsys.com>

diff --git a/board/synopsys/hsdk/fs-overlay/root/run_doom b/board/synopsys/hsdk/fs-overlay/root/run_doom
--- a/board/synopsys/hsdk/fs-overlay/root/run_doom
+++ b/board/synopsys/hsdk/fs-overlay/root/run_doom
@@ -4,6 +4,13 @@
 start() {
 	echo "Starting DOOM"
 	/usr/sbin/fbset > /etc/fb.modes
+        if [ $? -eq 0 ]
+        then
+                echo "fb mode is set"
+        else
+                echo "Error: Unable to set fb mode" >&2
+        fi
+
     	export SDL_NOMOUSE=1
 	/usr/bin/chocolate-doom &
 }
@@ -15,7 +22,13 @@ stop() {
         killall chocolate-doom
         sleep 2
         killall chocolate-doom
-        echo "OK"
+        if [ $? -eq 0 ]
+        then
+                echo "OK"
+        else
+                echo "Error: Unable to stop DOOM" >&2
+        fi
+
 }
 
 case "$1" in
diff --git a/board/synopsys/hsdk/fs-overlay/root/run_glmark b/board/synopsys/hsdk/fs-overlay/root/run_glmark
--- a/board/synopsys/hsdk/fs-overlay/root/run_glmark
+++ b/board/synopsys/hsdk/fs-overlay/root/run_glmark
@@ -2,14 +2,21 @@
 # start stop hotspot
 
 start() {
+	echo "Starting glmark2"
         export DISPLAY=:0
         glmark2 &
 }
 
 stop() {
-        echo "Killing glxgears"
+        echo "Killing glmark2"
         killall glmark2
-        echo "OK"
+        if [ $? -eq 0 ]
+        then
+                echo "OK"
+        else
+                echo "Error: Unable to stop glmark2" >&2
+        fi
+
 }
 
 case "$1" in
diff --git a/board/synopsys/hsdk/fs-overlay/root/run_glxgears b/board/synopsys/hsdk/fs-overlay/root/run_glxgears
--- a/board/synopsys/hsdk/fs-overlay/root/run_glxgears
+++ b/board/synopsys/hsdk/fs-overlay/root/run_glxgears
@@ -10,7 +10,13 @@ start() {
 stop() {
         echo "Killing glxgears"
         killall glxgears
-        echo "OK"
+        if [ $? -eq 0 ]
+        then
+                echo "OK"
+        else
+                echo "Error: Unable to stop glxgears" >&2
+        fi
+
 }
 
 case "$1" in
diff --git a/board/synopsys/hsdk/fs-overlay/root/set_wifi_config b/board/synopsys/hsdk/fs-overlay/root/set_wifi_config
--- a/board/synopsys/hsdk/fs-overlay/root/set_wifi_config
+++ b/board/synopsys/hsdk/fs-overlay/root/set_wifi_config
@@ -18,3 +18,10 @@ else
     sed -i "s/key_mgmt=NONE/psk=\"${2}\"/"  "$conf_path"
 fi 
 
+if [ $? -eq 0 ]
+then
+    echo "OK"
+else
+    echo "Error: Unable to edit /etc/wpa_supplicant.conf file" >&2
+fi
+
diff --git a/board/synopsys/hsdk/fs-overlay/root/wifi_connect b/board/synopsys/hsdk/fs-overlay/root/wifi_connect
--- a/board/synopsys/hsdk/fs-overlay/root/wifi_connect
+++ b/board/synopsys/hsdk/fs-overlay/root/wifi_connect
@@ -5,13 +5,31 @@ start() {
         # wpa_supplicant up
         echo "Connecting: "
 	wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
+	if [ $? -eq 0 ]
+	then
+		echo "OK"
+	else
+		echo "Error: Unable to start wpa_supplicant" >&2
+	fi
+
 	udhcpc -i wlan0
-        echo "OK"
+        if [ $? -eq 0 ]
+	then
+		echo "OK"
+	else
+		echo "FAIL: Unable to get IP address from access point" >&2
+	fi  
 }
 stop() {
         echo "Stopping hostapd"
         killall wpa_supplicant
-        echo "OK"
+        if [ $? -eq 0 ]
+        then
+                echo "OK"
+        else
+                echo "Error: Unable to stop wpa_supplicant" >&2
+        fi
+
 }
 
 case "$1" in
diff --git a/board/synopsys/hsdk/fs-overlay/root/wifi_hotspot b/board/synopsys/hsdk/fs-overlay/root/wifi_hotspot
--- a/board/synopsys/hsdk/fs-overlay/root/wifi_hotspot
+++ b/board/synopsys/hsdk/fs-overlay/root/wifi_hotspot
@@ -7,17 +7,36 @@ start() {
 	iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
 	iptables -A FORWARD -i eth0 -o wlan0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
 	iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
-	sleep 1
+        if [ $? -eq 0 ]
+        then
+                echo "Successfully setup iptables"
+        else
+                echo "Error: Unable to setup iptables" >&2
+        fi
+        sleep 1
+
 	
 	# Start hotspot
 	echo "Start hotspot:"
 	hostapd -B /etc/hostapd.conf
-	echo "OK"
+        if [ $? -eq 0 ]
+        then
+                echo "OK"
+        else
+                echo "Error: Unable to start hostapd" >&2
+        fi
+
 }
 stop() {
 	echo "Stopping hostapd"
 	killall hostapd
-	echo "OK"
+        if [ $? -eq 0 ]
+        then
+                echo "OK"
+        else
+                echo "Error: Unable to kill hostapd" >&2
+        fi
+
 }
 
 case "$1" in
